### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by blampe** [pulumi/pulumi-docker#649] opened 2023-05-31 21:05 UTC
### What happened?

```
Diagnostics:
  pulumi:pulumi:Stack (pulumi-service-bryce):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x101b7b290]
    goroutine 25 [running]:
    github.com/pulumi/pulumi-docker/provider/v4.diffUpdates(...)
    	/home/runner/work/pulumi-docker/pulumi-docker/provider/provider.go:276
    github.com/pulumi/pulumi-docker/provider/v4.(*dockerNativeProvider).Diff(0x140002b2c60?, {0x30?, 0x30?}, 0x1400087e930)
    	/home/runner/work/pulumi-docker/pulumi-docker/provider/provider.go:246 +0x4a0
    github.com/pulumi/pulumi-docker/provider/v4.dockerHybridProvider.Diff({{}, {0x102ae06e0, 0x26157, 0x26157}, {0x101dcde60, 0x6}, {0x102148b50, 0x1400087c780}, {0x102148aa0, 0x140002af950}}, ...)
    	/home/runner/work/pulumi-docker/pulumi-docker/provider/hybrid.go:120 +0xcc
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler.func1({0x10213cb48, 0x140007bbda0}, {0x10206f6a0?, 0x1400087e930})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.66.0/proto/go/provider_grpc.pb.go:555 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x10213cb48, 0x140007baea0}, {0x10206f6a0, 0x1400087e930}, 0x1400028cfe0, 0x1400049cfc0)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2f4
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler({0x1020cd2a0?, 0x140004d76d0}, {0x10213cb48, 0x140007baea0}, 0x1400087e8c0, 0x1400002df00)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.66.0/proto/go/provider_grpc.pb.go:557 +0x12c
    google.golang.org/grpc.(*Server).processUnaryRPC(0x14000022000, {0x102144cc0, 0x140005031e0}, 0x1400028aea0, 0x140007baae0, 0x102b22508, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1345 +0xc28
    google.golang.org/grpc.(*Server).handleStream(0x14000022000, {0x102144cc0, 0x140005031e0}, 0x1400028aea0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1722 +0x80c
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:966 +0x84
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:964 +0x278
```

### Expected Behavior

No panic :)

### Steps to reproduce

```
pulumi destroy -s ... --target 'urn:...' --target-dependents
```

This command was able to run successfully previously, but then it started consistently panicking. In the interim I had made some changes to my stack and run `docker system prune`.

### Output of `pulumi about`

```
Enabling the following internal features:
CLI
Version      3.68.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.29.0
aws-native  0.48.0
awsx        1.0.1
command     0.7.2
docker      4.2.3
nodejs      unknown
random      4.12.0
time        0.0.9
tls         4.6.1

Host
OS       darwin
Version  12.6.1
Arch     arm64

...

Backend
Name           pulumi.com
URL            https://app.pulumi.com/bryce-pulumi-corp
User           bryce-pulumi-corp
Organizations  bryce-pulumi-corp, pulumi

Dependencies:
NAME                              VERSION
@opensearch-project/opensearch    2.1.0
@pulumi/aws-native                0.48.0
@pulumi/awsx                      1.0.1
@pulumi/command                   0.7.2
@pulumi/docker                    4.2.3
@pulumi/random                    4.12.0
@pulumi/tls                       4.6.1
@pulumiverse/time                 0.0.9
@slack/client                     5.0.2
axios                             0.25.0
@swc/core                         1.3.21
@swc/jest                         0.2.23
@types/jest                       29.2.3
@types/node                       10.14.22
@types/which                      1.3.2
@typescript-eslint/eslint-plugin  5.36.2
@typescript-eslint/parser         5.36.2
eslint                            8.23.0
eslint-config-prettier            8.5.0
eslint-plugin-prettier            4.2.1
jest                              29.3.1
prettier                          2.7.1
typescript                        4.9.3
which                             2.0.2
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment] 2023-06-01 22:12
Closing as a duplicate, as this is also caused by the same circumstances described here: https://github.com/pulumi/pulumi-docker/issues/650#issuecomment-1572857163

**Closed by AaronFriel** 2023-06-01 22:12 UTC
Labels: resolution/duplicate, kind/bug, p0, impact/panic
