### ISSUE TITLE
Introduce a switch to build on Preview

### ISSUE THREAD

**Issue by stakauskas** [pulumi/pulumi-docker#850] opened 2023-11-16 11:56 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Trying to migrate to v4 pulumi/docker - noticed that this been introduced: 
`Images no longer are built during preview, reducing preview time significantly`

I would previously use:
```
if (isDryRun()) {

build images here
```

So that then on an actual deployment stage at `up`, you would have pre-built images to fetch and deploy, allowing to have: build / deploy stages separated and reducing the time of actual deploy, where longer preview time doesn't have any impact, and build images in preview mode would ensure that you would not have any build failures during deploy. 

Suggestion: introduce a switch to be able to build on `Preview`. 

### Affected area/feature

Docker Image Build in `Preview` mode.

**Comment by guineveresaenger** [comment] 2023-11-16 18:15
Dupe of #540

**Closed by guineveresaenger** 2023-11-16 18:15 UTC
Labels: kind/enhancement, resolution/duplicate
