### ISSUE TITLE
panic: interface conversion: interface {} is resource.PropertyMap, not *resource.Secret

### ISSUE THREAD

**Issue by blampe** [pulumi/pulumi-docker#650] opened 2023-06-01 15:37 UTC
### What happened?

```

    panic: interface conversion: interface {} is resource.PropertyMap, not *resource.Secret
    goroutine 56 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/resource.PropertyValue.SecretValue(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.56.0/go/common/resource/properties.go:440
    github.com/pulumi/pulumi-docker/provider/v4.parseCheckpointObject(...)
    	/home/runner/work/pulumi-docker/pulumi-docker/provider/provider.go:464
    github.com/pulumi/pulumi-docker/provider/v4.(*dockerNativeProvider).Diff(0x14000108c60?, {0x30?, 0x30?}, 0x1400012a700)
    	/home/runner/work/pulumi-docker/pulumi-docker/provider/provider.go:230 +0x6e4
    github.com/pulumi/pulumi-docker/provider/v4.dockerHybridProvider.Diff({{}, {0x1068c3b00, 0x25e12, 0x25e12}, {0x105bba018, 0x6}, {0x105f32070, 0x140000c8000}, {0x105f31fc0, 0x14000053e00}}, ...)
    	/home/runner/work/pulumi-docker/pulumi-docker/provider/hybrid.go:105 +0xcc
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler.func1({0x105f26088, 0x14000917a10}, {0x105e59820?, 0x1400012a700})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.56.0/proto/go/provider_grpc.pb.go:555 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x105f26088, 0x14000917560}, {0x105e59820, 0x1400012a700}, 0x140009b6340, 0x140005c26c0)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2f4
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler({0x105eb6b00?, 0x140000b9c20}, {0x105f26088, 0x14000917560}, 0x1400012a620, 0x140005da980)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.56.0/proto/go/provider_grpc.pb.go:557 +0x12c
    google.golang.org/grpc.(*Server).processUnaryRPC(0x140009fe000, {0x105f2e200, 0x14000502820}, 0x140003417a0, 0x14000330ea0, 0x106905508, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1336 +0xb38
    google.golang.org/grpc.(*Server).handleStream(0x140009fe000, {0x105f2e200, 0x14000502820}, 0x140003417a0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1704 +0x80c
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:965 +0x84
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:963 +0x278

  docker:index:Image (dbMigrationImage-amd64):
    error: error reading from server: EOF
```

### Expected Behavior

No panic :)

### Steps to reproduce

`pulumi up`

### Output of `pulumi about`

CLI
Version      3.68.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.29.0
aws-native  0.48.0
awsx        1.0.1
command     0.7.2
docker      4.1.2
nodejs      unknown
random      4.12.0
time        0.0.9
tls         4.6.1

Host
OS       darwin
Version  12.6.1
Arch     arm64

This project is written in nodejs: executable='/Users/bryce/.nvm/versions/node/v14.21.1/bin/node' version='v14.21.1'

...

Dependencies:
NAME                              VERSION
@opensearch-project/opensearch    2.1.0
@pulumi/aws-native                0.48.0
@pulumi/awsx                      1.0.1
@pulumi/command                   0.7.2
@pulumi/docker                    4.1.2
@pulumi/random                    4.12.0
@pulumi/tls                       4.6.1
@pulumiverse/time                 0.0.9
@slack/client                     5.0.2
axios                             0.25.0
@swc/core                         1.3.21
@swc/jest                         0.2.23
@types/jest                       29.2.3
@types/node                       10.14.22
@types/which                      1.3.2
@typescript-eslint/eslint-plugin  5.36.2
@typescript-eslint/parser         5.36.2
eslint                            8.23.0
eslint-config-prettier            8.5.0
eslint-plugin-prettier            4.2.1
jest                              29.3.1
prettier                          2.7.1
typescript                        4.9.3
which                             2.0.2

Pulumi locates its logs in /var/folders/kq/zdlx0fn57yl66gxktcyzylv40000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment] 2023-06-01 22:11
After conferring with @justinvp, we think this and #649 are pulumi/pulumi#12964. 

* The panics can only occur if the Image resource's output named `__inputs` is not a `resource.SecretProperty(resource.ObjectProperty...)`
* The provider always constructs `__inputs` as such: https://github.com/pulumi/pulumi-docker/blob/a3cd4fc285bbd6afd2b016ea066100cb013ac79a/provider/provider.go#L440-L445
  * This code has been used in all 4.x releases
* The checkpoint @blampe provided showed that some Image resources were not generated by the provider, but mutated by the engine in the related Pulumi issue.

Given this, we're closing this as a duplicate of #12964. If anyone encounters this issue in the wild, please let us know, we're working on a workaround. Fortunately this appears limited to users using `pulumi destroy --target` for specific Pulumi releases.

**Closed** 2023-06-01 22:42 UTC
Labels: resolution/duplicate, kind/bug, p0, impact/panic

**Comment by blampe** [comment] 2023-06-02 21:02
For anyone else affected, you can restore your stack to a good state like so:
1. Make sure your CLI is up-to-date, or at least version 3.68.
2. Export your stack's checkpoint: `pulumi stack -s ... export > state.json`.
3. Make a copy of that state, just in case: `cp state.json state.json.bak`.
4. Manually repair `state.json`: for every resource with `"type": "docker:index/image:Image"`, remove the `"__inputs"` key from `"outputs"`.

```diff
{
    "urn": "...",
    "custom": true,
    "id": "...",
    "type": "docker:index/image:Image",
    "inputs": {
        ...
    },
    "outputs": {
-       "__inputs": {
-           ...
-       },
        "baseImageName": "...",
        "context": "...",
        "dockerfile": "...",
        "imageName": "...",
        "registryServer": "...",
        "repoDigest": "..."
    },

```

5. Load the fixed state back into your stack: `pulumi stack import -s ... --file state.json`.
