### ISSUE TITLE
Including grpc in pulumi docker image

### ISSUE THREAD

**Issue by sombrastudios** [pulumi/pulumi-docker#113] opened 2019-11-20 12:20 UTC
Good day everyone.

I'd welcome to have the `grpc` libraries installed in the pulumi docker image.

Simply using `npm install grpc` or `pip install grpcio` installs the c libraries along with the domain-specific libraries.

Reason:

I pretty quickly stumbled into problems without it. 
Considering I should have a pretty simple setup, I assume it was (maybe?) needed to talk to Kubernetes in GKE. Regrettably, I had problems setting up a minimal working example. I decided to just go ahead and ask and state, what I know

**Comment by chrsmith** [comment] 2019-11-20 16:36
Yes, this is a reasonable request and I'll look into what we can do here. Unfortunately installing `grpc` at the system-level might not be enough. (Since you'd still need the related `npm` packages, and those might not "detect" or "honor" any `gprc` binaries already installed on the system.)

But the grpc bits are one of the more complex dependencies that the typical Pulumi program needs to pull down. So if it is possible to simply bake that into the container image then it would be a good improvement.

Thank you for filing the issue.

**Comment by chrsmith** [comment] 2019-12-17 19:52
I'm going to close this out as "working as intended", although that isn't the full story.

I don't think there is a standard way to install the gRPC dependency, as it may be specific to the language runtime(s). e.g. NPM would install it globally in one place, (maybe `yarn` in another), and if you are using Python or .NET there are _other_ places where it would be expected.

Also, the gRPC bits need to be versioned along with the libraries that use them. (e.g. if we did install gRPC at the system level, it could an incompatible version to what your program needs.)

The only good way I can see us solving this is to just ensure that you can run the "gather dependencies" step before running Pulumi, e.g. `npm install` or `pip3 install -r requirements.txt`. 

We have the right hook available in the `pulumi/actions` container so things "just work":

- [documentation](https://www.pulumi.com/docs/guides/continuous-delivery/github-actions/)
- [entrypoint.sh](https://github.com/pulumi/pulumi/blob/master/dist/actions/entrypoint.sh)

But as far as the "base" `pulumi/pulumi` Docker container, I don't think we can properly solve this without installing N-different versions of the gRPC libraries and/or have various language runtimes properly detect and use any pre-baked versions.

So if you aren't using GitHub Actions for your deployments, I think you'll just need to update your `Dockerfile`'s `CMD` or `ENTRYPOINT` to gather up your Pulumi program's dependencies before invoking `pulumi`.

**Closed by chrsmith** 2019-12-17 19:52 UTC
