### ISSUE TITLE
[csharp] unable to create explicit docker provider

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-docker#640] opened 2023-05-18 17:01 UTC
### What happened?

When creating an explicit docker provider in csharp, the program panics.

### Expected Behavior

Create an explicit docker provider.

### Steps to reproduce

1. `pulumi new csharp`
2. `dotnet add package Pulumi.Docker`
3. Execute the below program

```csharp
using System.Collections.Generic;
using Pulumi;

return await Deployment.RunAsync(() =>
{
   var provider = new Pulumi.Docker.Provider("docker", new Pulumi.Docker.ProviderArgs
   {
      Host = "host",
      RegistryAuth = new List<Pulumi.Docker.Inputs.ProviderRegistryAuthArgs>
      {
         new Pulumi.Docker.Inputs.ProviderRegistryAuthArgs
         {
            Address = "",
            Username = "",
            Password = ""
         }
      }
   });

   return new Dictionary<string, object?>
   {
      ["outputKey"] = "outputValue"
   };
});

```

### Output of `pulumi about`

Version      3.67.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME    VERSION
docker  4.2.0
dotnet  unknown

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment] 2023-05-18 17:41
I've root-caused this to the provider incorrectly communicating acceptsSecrets: true to the engine; which makes the engine send Password encoded as secret back to the Configure call. Bridged providers do not expect and are not prepared to handle secrets in Configure, causing this issue.

Got a fix coming shortly.

**Comment by t0yv0** [comment] 2023-05-19 00:02
Fixed in https://github.com/pulumi/pulumi-docker/releases/tag/v4.2.1

**Comment by phillipedwards** [comment] 2023-05-19 13:43
@t0yv0 I'm reopening because I am seeing the same panic in 4.2.1 with the same repro.

`dotnet list package`
```
   [net7.0]: 
   Top-level Package      Requested   Resolved
   > Pulumi                    3.*         3.54.1  
   > Pulumi.Docker        4.2.1       4.2.1  
```

panic
```
  pulumi:pulumi:Stack (dev):
    panic: Error reading level config: '' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[4dabf18193072939515e22adb298388d:1b47061264138c4ac30d75fd1eb44270 value:]'
    goroutine 51 [running]:
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0xc000149180, {0xc0004e3a60, 0x1, 0x1}, 0x0?)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20221122203342-430f685de305/helper/schema/resource_data.go:553 +0x328
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).getChange(0x159b85e?, {0x15a16ad?, 0xd?}, 0x98?, 0xeb?)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20221122203342-430f685de305/helper/schema/resource_data.go:524 +0x1b8
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).diffChange(0x0?, {0x15a16ad?, 0xc00061ec50?})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20221122203342-430f685de305/helper/schema/resource_data.go:501 +0x76
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diffSet(0x159b85e?, {0x17f1e98, 0xc0000400b0}, {0x15a16ad, 0xd}, 0xc00071b180, 0xc00061f0e8, {0x17f8490?, 0xc000149180?}, 0x0)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20221122203342-430f685de305/helper/schema/schema.go:1413 +0x90
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0x6?, {0x17f1e98, 0xc0000400b0}, {0x15a16ad, 0xd}, 0xc00071b180, 0xc000149100, {0x17f8490?, 0xc000149180}, 0x0)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20221122203342-430f685de305/helper/schema/schema.go:1135 +0x265
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc0006d12f0, {0x17f1e98, 0xc0000400b0}, 0x0, 0xc00051dfb0, 0x0, {0x0, 0x0}, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20221122203342-430f685de305/helper/schema/schema.go:679 +0x353
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).Configure(0xc0000ad320, {0x17f1e98, 0xc0000400b0}, 0x0?)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20221122203342-430f685de305/helper/schema/provider.go:276 +0xe5
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Configure({0xc0000ad320?, {0x0?, 0x0?, 0x0?}}, {0x17e6ea0?, 0xc00051dfb0?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.47.2/pkg/tfshim/sdk-v2/provider.go:88 +0x5b
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Configure(0xc0006c7680, {0x17f1f08?, 0xc00051dad0?}, 0xc0005ab100)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.47.2/pkg/tfbridge/provider.go:538 +0xd4
    github.com/pulumi/pulumi-docker/provider/v4.dockerHybridProvider.Configure({{}, {0x21b7ca0, 0x26157, 0x26157}, {0x17dd3fc, 0x6}, {0x17fe470, 0xc0006c7680}, {0x17fe3c0, 0xc0007c8dc0}}, ...)
        /home/runner/work/pulumi-docker/pulumi-docker/provider/hybrid.go:87 +0x17c
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Configure_Handler.func1({0x17f1f08, 0xc00051dad0}, {0x14c4e00?, 0xc0005ab100})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.64.0/proto/go/provider_grpc.pb.go:462 +0x78
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x17f1f08, 0xc00051d5f0}, {0x14c4e00, 0xc0005ab100}, 0xc000284400, 0xc000010df8)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Configure_Handler({0x153bb40?, 0xc000396b40}, {0x17f1f08, 0xc00051d5f0}, 0xc00019ae70, 0xc000571040)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.64.0/proto/go/provider_grpc.pb.go:464 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00076e000, {0x17fa100, 0xc000412000}, 0xc000172240, 0xc00016dbc0, 0x21f98e8, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf3
    google.golang.org/grpc.(*Server).handleStream(0xc00076e000, {0x17fa100, 0xc000412000}, 0xc000172240, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1722 +0xa36
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:966 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:964 +0x28a
```

**Comment by t0yv0** [comment] 2023-05-19 17:26
Thanks for reopening, indeed it is not fixed yet, I need to take another look. I believe I did the "repro-test-fix" cycle with the help of ProgramTest but I must have somehow failed to verify that the ProgramTest reproduces the issue. Due to https://github.com/pulumi/pulumi/issues/12981 problem the test is actually green in CI and didn't prevent the release from going out.

**Closed** 2023-05-22 19:45 UTC
Labels: resolution/fixed, language/dotnet, p1, kind/bug

**Comment by t0yv0** [comment] 2023-05-22 20:24
v4.2.2  coming up shortly with the fix. Thank you!

**Comment by t0yv0** [comment] 2023-05-23 13:37
https://github.com/pulumi/home/issues/2877
