### ISSUE TITLE
docker.Image: Cannot connect to the Docker daemon because my socket address is different

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-docker#619] opened 2023-05-02 12:49 UTC
### What happened?

When running a simple Pulumi program, I get the following error even though Docker is running:

```text
Diagnostics:
  docker:index:Image (demo-image):
    error: 1 error occurred:
        * Error pinging Docker server: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### Expected Behavior

No error.

### Steps to reproduce

```typescript
const demoImage = new docker.Image("demo-image", {
    build: {
        context: ".",
        dockerfile: "Dockerfile",
    },
    imageName: "username/image:tag1",
    skipPush: true,
});
```

```dockerfile
FROM alpine:3.14
```

### Output of `pulumi about`

```text
CLI          
Version      3.65.1
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.101.0
docker        4.2.0
nodejs        unknown
random        4.13.0

Host     
OS       darwin
Version  13.3.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v19.5.0'

Current Stack: jkodrofftest/test-fix-tempalte/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/jkodroff
User           jkodroff
Organizations  jkodroff, jkodrofftest, zephyr, demo, pulumi

Dependencies:
NAME                  VERSION
@pulumi/docker        4.2.0
@pulumi/pulumi        3.65.1
@pulumi/random        4.13.0
@types/node           16.18.25
@pulumi/azure-native  1.101.0

Pulumi locates its logs in /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/ by default

```

### Additional context

Debugged this with @guineveresaenger and @AaronFriel for a while, and we did not come up with an obvious cause. We:

* verified that Docker is definitely running on my machine
* tried a reboot
* grabbed the output of a few Docker commands, no obvious cause
* verified that @guineveresaenger does not see the same issue with this program
* verified that v4.1.x behaves the same
* verified that v3.latest _does not_ exhibit the bug
* tried blowing away my `~/.docker/config.json`, same result
* verified that I do not have `DOCKER_HOME` set (or whatever the env var is)

Some info about my machine:

<img width="271" alt="image" src="https://user-images.githubusercontent.com/410614/235669855-7bcdeaeb-a7fc-4702-8bf2-4c7708351b9d.png">

And here's my `docker info` dump:

```text
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /Users/jkodroff/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /Users/jkodroff/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/jkodroff/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     /Users/jkodroff/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     /Users/jkodroff/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/jkodroff/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/jkodroff/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.10.0
    Path:     /Users/jkodroff/.docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.841GiB
 Name: docker-desktop
 ID: d9eba96f-5d82-413d-aa48-776906674f45
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkodroff** [comment] 2023-05-02 20:12
As requested by @AaronFriel and @guineveresaenger:

```bash
docker context list
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                                  KUBERNETES ENDPOINT   ORCHESTRATOR
default *           moby                Current DOCKER_HOST based configuration   unix:///Users/jkodroff/.docker/run/docker.sock
desktop-linux       moby                                                          unix:///Users/jkodroff/.docker/run/docker.sock
```

**Comment by jkodroff** [comment] 2023-05-02 20:14
I was able to work around the issue with the following suggestion:

```bash
export DOCKER_HOST=unix:///Users/jkodroff/.docker/run/docker.sock
```

**Comment by guineveresaenger** [comment] 2023-05-02 23:01
Thank you for filing this issue, Josh - glad we got a workaround figured out for you.

It seems that somehow your setup wasn't hooking up your provider to the `desktop-linux` host. I have not been able to reproduce this issue on my intel mac, with the same docker context setup.

Nonetheless, we should do some digging here to improve the experience for others who might run into this.

**Comment by jkodroff** [comment] 2023-05-03 16:46
If you look at the `docker context list`output, you'll notice that in both cases, my socket is in my home directory (and yes - I have zero idea how my docker setup got to this state).

I think we could make it better if we detect the ol; "cannot connect to the Docker daemon" error message and annotate something like:

> You may need to set the `DOCKER_HOME` environment variable. Run the `docker context list` command and ensure that the socket address in the above error message matches the `DOCKER ENDPOINT` value of your current context. If it doesn't set `DOCKER_HOME` to your context's endpoint.

Since we don't really know how I got here (and it wasn't by doing anything particularly weird - I don't use Docker for Mac much), the above wordy advice is probably best.

I would've been happiest if this went in the actual error message, but if that's not easy to do, "Installation and Configuration" in the Registry would've been the second place I would've looked.

**Comment by blampe** [comment] 2023-05-03 17:46
@jkodroff which version of Docker Desktop are you using?

I also ran into this, and I suspect it's because with Docker Desktop 4.18 they now [default](https://www.docker.com/blog/docker-desktop-4-18/) to an admin-less install -- so they drop the socket in your user directory instead of under `/var/run`.

Explicitly setting `DOCKER_HOST` also worked for me, but it would be a good quality of life improvement if the provider could detect whether Docker was running in a privileged or non-privileged mode.

**Comment by guineveresaenger** [comment] 2023-05-03 17:51
oooohhhhh! I'm running 4.17 still 😱 this is good to know!

**Comment by jkodroff** [comment] 2023-05-04 19:26
@blampe 4.19. Methinks we've figured out the cause!

**Comment by guineveresaenger** [comment] 2023-05-04 23:58
somewhat related: https://github.com/kreuzwerker/terraform-provider-docker/issues/540

**Comment by liamawhite** [comment] 2023-06-07 19:36
As an fyi for anyone who runs into this you can turn the default back on by ticking `Allow the default Docker socket to be used`

![Screenshot 2023-06-07 at 12 30 35 PM](https://github.com/pulumi/pulumi-docker/assets/14291598/96dc0b0e-6a85-45a9-92d9-a87b07c6f2fc)

**Comment by joeduffy** [comment] 2023-06-27 23:51
I just hit this too! It sounds like the default installation of newer versions of Docker guarantees someone will hit this problem?

**Comment by jkodroff** [comment] 2023-07-07 19:38
@joeduffy Yes, that's correct.

**Comment by AaronFriel** [comment] 2023-07-08 02:32
@guineveresaenger is there a library call we can make to Docker to grab the config value it uses for the docker socket?

**Comment by AaronFriel** [comment] 2023-07-08 02:32
I've marked this as a P1 - it looks like this will fail by default on new Docker Desktop for Mac installs.

**Closed** 2023-07-26 19:02 UTC
Labels: p1, kind/bug, impact/first-48
