### ISSUE TITLE
Wrong Go data type reference

### ISSUE THREAD

**Issue by pasdam** [pulumi/pulumi-docker#375] opened 2022-07-17 08:21 UTC
File: [themes/default/content/registry/packages/docker/api-docs/getregistryimage/_index.md](https://www.pulumi.com/registry/packages/docker/api-docs/getregistryimage/)

In the go code snippet
```diff
- ubuntuRegistryImage, err := docker.LookupRegistryImage(ctx, &GetRegistryImageArgs{
+ ubuntuRegistryImage, err := docker.LookupRegistryImage(ctx, &docker.LookupRegistryImageArgs{
```

**Comment by stack72** [comment] 2022-08-03 13:07
Closing this as a duplicate of the related bug https://github.com/pulumi/pulumi/issues/10309

**Closed by stack72** 2022-08-03 13:07 UTC
Labels: resolution/duplicate, kind/bug
