### ISSUE TITLE
DEPRECATION: pulumi-docker is being installed using the legacy 'setup.py install' method

### ISSUE THREAD

**Issue by basictheprogram** [pulumi/pulumi-docker#415] opened 2022-11-06 16:59 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

DEPRECATION: pulumi-docker is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

**Comment by viveklak** [comment] 2022-11-07 21:24
Duplicate of https://github.com/pulumi/pulumi/issues/11267

**Closed** 2022-11-07 21:25 UTC
Labels: kind/enhancement, resolution/duplicate
