### ISSUE TITLE
docker.Image: An image does not exist locally with the tag

### ISSUE THREAD

**Issue by mszewczyk-ipwt** [pulumi/pulumi-docker#573] opened 2023-03-28 12:25 UTC
### What happened?

When building and pushing docker image I get an error:
```
  docker:index:Image (sample_deployment_image):
    error: An image does not exist locally with the tag: some.ecr.repository.aws.com/subdirectory/sample_deployment_image
```

### Expected Behavior

Image should be built and pushed

### Steps to reproduce

I am using outputs from other resources:
```
  def sample_deployment_image():
    return pulumi_docker.Image(
      "sample_deployment_image",
      image_name=some_ecr_repository.repository_url.apply(
        lambda url: f"{url}:0.1"
      ),
      build=dict(
        context='files/docker/sample_deployment_image',
        dockerfile='files/docker/sample_deployment_image/Dockerfile',
        platform='linux/amd64',
      ),
      registry=dict(
        server=some_ecr_repository.repository_url.apply(
          lambda url: url.split('/')[0]
        ),
        username='AWS',
        password=get_ecr_token(),
      ),
      opts=ResourceOptions(
        replace_on_changes=[
          'image_name'
        ],
        delete_before_replace=True,
      )
    )
```
but also if I just type variables as strings I get the same result:
```
  def sample_deployment_image():
    return pulumi_docker.Image(
      "sample_deployment_image",
      image_name=some.ecr.repository.aws.com/subdirectory/sample_deployment_image:0.1
      build=dict(
        context='files/docker/sample_deployment_image',
        dockerfile='files/docker/sample_deployment_image/Dockerfile',
        platform='linux/amd64',
      ),
      registry=dict(
        server="some.ecr.repository.aws.com",
        username='AWS',
        password="PlaceAwsEcrGet-Login-PasswordOutputHere",
      ),
      opts=ResourceOptions(
        replace_on_changes=[
          'image_name'
        ],
        delete_before_replace=True,
      )
    )
```

### Output of `pulumi about`

```
CLI          
Version      3.44.3
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.26.0
aws-native  0.49.0
cloudflare  4.15.0
docker      4.1.0
github      5.5.0
kubernetes  3.23.1
python      unknown

Host     
OS       arch
Version  
Arch     x86_64

This project is written in python: executable='/usr/sbin/python3' version='3.10.10
'

Current Stack: base

TYPE                                                 URN
Don't want to share this part for security concerns


Found no pending operations associated with base

Backend        
Name           example
URL            s3://some-aws-bucket
User           mszewczyk-ipwt
Organizations  

Dependencies:
NAME               VERSION
boto3              1.26.56
GitPython          3.1.31
netaddr            0.8.0
pip                22.3.1
pulumi-aws         5.26.0
pulumi-aws-native  0.49.0
pulumi-cloudflare  4.15.0
pulumi-docker      4.1.0
pulumi-github      5.5.0
pulumi-kubernetes  3.23.1
pyOpenSSL          23.0.0
setuptools         65.5.0

Pulumi locates its logs in /tmp by default
```

### Additional context

As for OS I'm using latest version of Arch Linux and Docker version 23.0.1, build a5ee5b1dfc. All other settings are default.
Strange thing is that pulumi reports image being built, but in `docker images -a` I have no images. `DOCKER_HOST` is default and even putting `docker.Provider` in code with `host="unix:///var/run/docker.sock"` does not solve the problem.
Also upgrading pulumi CLI and python package to newest (currently 3.60.0) version did not help.

**Comment by guineveresaenger** [comment] 2023-03-28 23:54
Hi @mszewczyk-ipwt - thank you for filing this issue.
When this error appears in Docker, it is usually caused by a malformatted image name, and ECR especially is fairly picky on format.
It is curious that you say that `docker images` has no output for you locally.

Could you try the following to help us identify possible causes:

1. Try running this without the ResourceOptions, and see if that yields better results.

2. Try setting `skip_push = true` and then report on the outcome of `docker images`. Curious if that will build locally, and what the image name will be.

**Comment by ShedPlant** [comment] 2023-03-29 11:13
I have also seen this same error today twice, shortly after upgrading to `pulumi-docker` `4.0.0`.
Although it has _usually_ worked with `4.0.0`, so I don't know under what circumstances to reproduce 😞 .

**Comment by ShedPlant** [comment] 2023-04-06 10:34
@guineveresaenger any idea what's happening on this issue? I can reproduce it at least, as per [above comment](https://github.com/pulumi/pulumi-docker/issues/573#issuecomment-1494095124).

For now my workaround is to downgrade to `pulumi-docker` `3` for the affected projects 😞 .
Another hypothetical workaround would be to `docker pull` (and or `docker build`?) before running `pulumi up`, but if I did that I may as well not use `pulumi-docker` at all 😞 .

**Comment by rtrindvg** [comment] 2023-05-19 20:57
Any updates on this issue? This is basically making it impossible to use the v4 version on our projects, since it breaks the CI workflow.

**Comment by blaise-bradley** [comment] 2023-05-22 17:32
Just wanted to chime in with a "me too" here. I'm seeing something very similar to what @ShedPlant is describing above. I am able to build and push successfully on my Mac, but my program fails on Github Actions using latest Ubuntu. The console output looks similar too -- seems as though Pulumi is attempting to push the image before the build is complete.

**Comment by guineveresaenger** [comment] 2023-05-22 21:48
Hi everyone!
Thank you all for elaborating on this issue - I cannot tell if @mszewczyk-ipwt is seeing this in CI or not, but it sounds like everyone else is seeing this.

Two questions:

1. Do you all see this using AWS ECR? Or does it happen on other registries as well?
2. Are all of you seeing this when using GitHub Actions? Or are other CI systems involved?

**Comment by rtrindvg** [comment] 2023-05-22 21:51
On my case, it's Azure ACR, so different registries are suffering from the same issue. Unfortunately, this is on Github Actions as well, so I can't talk about other CI systems.

A colleague of mine had the same error on his machine, but we could not reproduce the error again, so it seems possible to happen outside of CI sytems as well on some unknown condition.

**Comment by blaise-bradley** [comment] 2023-05-22 22:18
Thanks for taking a look @guineveresaenger! 

In my case, yes this is:

1.  AWS ECR
2. Github Actions

**Comment by guineveresaenger** [comment] 2023-05-23 20:55
Hi everyone!

I cannot reproduce this behavior unfortunately. I [recreated the situation described with a minimal TypeScript example and GitHub Actions, on AWS](https://github.com/guineveresaenger/573-repro). I'm really curious what the differences here are.

I used a fairly large image to ensure it would take a while to build as well.

**Comment by rtrindvg** [comment] 2023-05-23 21:28
Curious, thanks for the repro repository. 

I believe the package "@pulumi/docker" is missing from both package.json and yarn.lock. Can you add this to your repro case so we can better try to isolate the difference between your repro and our use cases?

**Comment by ShedPlant** [comment] 2023-05-24 08:05
You should be able to repro from https://github.com/curoo/pulumi-docker-investigations/tree/master/issues/issue_573

**Comment by guineveresaenger** [comment] 2023-05-24 15:54
hi @ShedPlant - I really appreciate that repro and all your efforts in general! However, as there's some extra things in there, I don't really follow the precise situation that may trigger this issue. Are you saying that you only encounter this behavior when loading a database schema into your image? Or when pulling from upstream cache? Having more context here would be helpful, as it seems the base case works fine.

@rtrindvg  - apologies; the version is set in package.json now. 👍

**Comment by ShedPlant** [comment] 2023-05-24 16:03
> Are you saying that you only encounter this behavior when loading a database schema into your image?

Yes, I've personally only seen this problem when loading a database schema into a postgresql image.
But I can't guarantee that's the only way to encounter it.

From the logs, it looks like the docker build was _still_ running the below command when it tried to push prematurely.
```
RUN cp docker-entrypoint.sh docker-entrypoint.sh.old && \
    sed -i '/exec gosu postgres "$@"/ d' docker-entrypoint.sh && \
    sed -i '/exec "$@"/ d' docker-entrypoint.sh && \
    ./docker-entrypoint.sh postgres && \
    mv docker-entrypoint.sh.old docker-entrypoint.sh
```

For info, why am I doing this:
The postgresql `docker-entrypoint.sh` tries to load `schema.sql` on startup.
But for a very large schema this means every time I start the image, it's slow. And I haven't proved my schema loads correctly.
Instead I want to load the schema once at build time, so downstream consumers of the image can start it quickly.
This solution to hack the `docker-entrypoint.sh`, load the schema, then restore `docker-entrypoint.sh`, was already in place and working with to `pulumi-docker` `3.x`.

**Comment by blaise-bradley** [comment] 2023-05-24 20:21
> From the logs, it looks like the docker build was still running the below command when it tried to push prematurely.

I'm pretty confident this is true for me as well. In my case, it seems like we try to push during the command `RUN yarn install`. 

I spent a good chunk of time trying to repro by starting from the provided minimal project, but have so far only been able to repro with my entire project. Here's what I've learned:

1. I'm able to get the repro project to work when installing only some of my project's dependencies
2. This doesn't seem to be just an "amount of time" thing. Even when `yarn install` takes a long time to install the working subset of my dependencies, the build still works.

My working theory is that a specific subset of my dependencies do _something_ (e.g. a post-install shell script) that makes Pulumi and/or Docker believe the build has completed even though it hasn't. Given the number of dependencies, tracking down the culprit(s) would be really time consuming. 

Would be curious if there were modifications to @ShedPlant's schema that would allow their build to complete (e.g. just the table create, or fewer inserts) or if it's the act of running the SQL that causes it to fail. Would also be curious to see if a version that didn't have the file copy and rename operations would work.

**Comment by AaronFriel** [comment] 2023-05-25 23:51
@mszewczyk-ipwt @blaise-bradley @ShedPlant et al: can you provide `docker info` and `docker version` output in your environments? Feel free to redact information, but especially we want to know:

1. Version of the Docker *engine* or host
2. Support for Buildkit
3. Nature of the connection to the Docker engine or host (file or TCP socket, SSH)

We're unable to reproduce this, so it's helpful to correlate any meaningful signals we can.

**Comment by ShedPlant** [comment] 2023-05-26 08:08
https://github.com/curoo/pulumi-docker-investigations/actions/runs/5088611591/jobs/9145233883

`pulumi-docker` version is `4.1.1`.

`docker info`:
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., 0.10.4+azure-1)
  compose: Docker Compose (Docker Inc., 2.[17](https://github.com/curoo/pulumi-docker-investigations/actions/runs/5088611591/jobs/9145233883#step:13:18).3+azure-1)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: [18](https://github.com/curoo/pulumi-docker-investigations/actions/runs/5088611591/jobs/9145233883#step:13:19)
 Server Version: 20.10.24+azure-1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: 860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-1037-azure
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 6.781GiB
 Name: fv-az397-676
 ID: 45C5:GCD5:C2ZA:BU76:2JJE:VILT:FJER:O74A:S3LH:GA6O:RCDR:J762
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: githubactions
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  1[27](https://github.com/curoo/pulumi-docker-investigations/actions/runs/5088611591/jobs/9145233883#step:13:28).0.0.0/8
 Live Restore Enabled: false
```

`docker version`
```
Client:
 Version:           20.10.24+azure-1
 API version:       1.41
 Go version:        go1.19.6
 Git commit:        297e1284d3bd092e9bc96076c3ddc4bb33f8c7ab
 Built:             Fri Mar 31 18:34:38 UTC 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.24+azure-1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.6
  Git commit:       5d6db842238e3c4f5f9fb9ad70ea46b35227d084
  Built:            Tue Apr  4 18:03:51 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20+azure-1
  GitCommit:        2806fc1057397dbaeefbea0e4e[17](https://github.com/curoo/pulumi-docker-investigations/actions/runs/5088611591/jobs/9145233883#step:14:18)bddfbd388f38
 runc:
  Version:          1.1.7
  GitCommit:        860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 docker-init:
  Version:          0.[19](https://github.com/curoo/pulumi-docker-investigations/actions/runs/5088611591/jobs/9145233883#step:14:20).0
  GitCommit:
```

**Comment by blaise-bradley** [comment] 2023-05-26 16:16
Strangely, when I added steps to my Github Action to output docker info and version (shared below) my build started working. It seems as though running the `docker` command before running `pulumi` "fixes" the problem in my case. The error reoccurs when I remove those steps from my workflow, however. I will probably just move ahead with this workaround for now, but will check back here in case you're able to discover the root cause.

One other potentially relevant detail is that I'm using the [Setup QEMU action](https://github.com/docker/setup-qemu-action), as I'm trying to build a `linux/arm64` image.


`docker info`:

`Client:
 Context:    default
 Debug Mode: true
 Plugins:
  buildx: Docker Buildx (Docker Inc., 0.10.4+azure-1)
  compose: Docker Compose (Docker Inc., 2.[17](***).3+azure-1)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 19
 Server Version: 20.10.24+azure-1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: 860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-1037-azure
 Operating System: ***
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 6.781GiB
 Name: fv-az452-355
 ID: 45C5:GCD5:C2ZA:BU76:2JJE:VILT:FJER:O74A:S3LH:GA6O:RCDR:J762
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: githubactions
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
 Live Restore Enabled: false`
 
 `docker version`:
 
 `Client:
 Version:           20.10.24+azure-1
 API version:       1.41
 Go version:        go1.19.6
 Git commit:        297e1284d3bd092e9bc96076c3ddc4bb33f8c7ab
 Built:             Fri Mar 31 18:34:38 UTC 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.24+azure-1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.6
  Git commit:       5d6db842238e3c4f5f9fb9ad70ea46b35227d084
  Built:            Tue Apr  4 18:03:51 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20+azure-1
  GitCommit:       ***
 runc:
  Version:          1.1.7
  GitCommit:        ***
 docker-init:
  Version:        ***
  GitCommit:

**Comment by blaise-bradley** [comment] 2023-05-26 17:05
Edit to my previous comment: looks the build now works only intermittently.

**Comment by abinba** [comment] 2023-08-12 08:48
Is there any update on this issue? Having the same issue with pulumi-docker==4.3.1

**Comment by abinba** [comment] 2023-08-19 14:39
Here're my error logs:

```
 +  docker:index:Image magic-stack  Building your image for linux/amd64 architecture.
 +  docker:index:Image magic-stack creating (0s) Building your image for linux/amd64 architecture.
 +  docker:index:Image magic-stack creating (0s) Building the image
 +  docker:index:Image magic-stack creating (1s) Installing dependencies using pip > requirements.txt
@ updating..................
 +  docker:index:Image magic-stack creating (18s) Pushing Image to the registry
 +  docker:index:Image magic-stack creating (18s) The push refers to repository [***.dkr.ecr.***.amazonaws.com/magic-75cbdbf]
 +  docker:index:Image magic-stack creating (18s) error: An image does not exist locally with the tag: ***.dkr.ecr.***.amazonaws.com/magic-75cbdbf
 +  docker:index:Image magic-stack **creating failed** error: An image does not exist locally with the tag: ***.dkr.ecr.***amazonaws.com/magic-75cbdbf
 +  pulumi:pulumi:Stack magic-stack creating (20s) error: update failed
 +  pulumi:pulumi:Stack magic-stack **creating failed (0.01s)** 1 error
```

I have been debugging a lot and it appears that this error was caused (in my case) by error produced by `pip` failing in Dockerfile, but the build being successfull.

My Dockerfile looked something like this:
```
FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE=1 \
         PYTHONUNBUFFERED=1

# Install Python deps
RUN /usr/bin/bash /tmp/install_dependencies.sh <-- it fails here

CMD ["handler.run"]
```

`install_dependencies.sh` (just an example)
```
#!/bin/bash

python -m pip install some-failing-package -q
```

It doesn't fail because I'm running it with quiet option. As a result, docker couldn't push because of this error, but I'm still not sure why.

I have been able to fix it with just deleting the failing package (I didn't actually need it). Hope this helps someone who's facing this issue.

**Comment by rtrindvg** [comment] 2023-08-29 14:43
It's curious, but I don't see the issue anymore on any of our several repositories. If it happens again I will try to provide more information about it here to contribute with the issue reproduction.

**Comment by kuperiu** [comment] 2023-09-15 11:01
I had the same issue. Pulumi worked locally and not on Github Actions.
The reason was that the build failed on Github actions because of missing permissions.
Basically if the build fails Pulumi still tries to push the image but it doesn't exist.
It should be fixed

**Comment by ShedPlant** [comment] 2023-09-15 13:29
> I had the same issue. Pulumi worked locally and not on Github Actions. The reason was that the build failed on Github actions because of missing permissions. Basically if the build fails Pulumi still tries to push the image but it doesn't exist. It should be fixed

I don't understand - missing permissions to what?

Also by "It should be fixed" you mean "it's broken, please fix it", not "it is fixed now", right? 😅

**Comment by kuperiu** [comment] 2023-09-20 08:45
@ShedPlant  In my case the docker build did a mvn install and it got all the dependcies from aws codeartifact. 
The github runner was missing an IAM permission to codeartifact and it failed because of it.
The only error that I got was "An image does not exist locally with the tag" and it's very misleading. I think it should be changed and show the real error from the docker file, in my case that the authorization failed

**Closed** 2023-11-21 18:28 UTC
Labels: resolution/fixed, kind/bug

**Comment by ShedPlant** [comment] 2023-11-24 09:06
Thanks! I'll try it out soon.
