### ISSUE TITLE
ServiceTaskSpecContainerSpecArgs.Commands should be `Command`

### ISSUE THREAD

**Issue by koliyo** [pulumi/pulumi-docker#234] opened 2020-10-09 06:27 UTC
To be consistent with `ContainerArgs.Command`, both should use singular `Command` instead of `Commands`?

**Comment by leezen** [comment] 2020-10-09 22:13
Thanks for pointing out this inconsistency. Probably yes, but at this point it would be a breaking change to rename it as such. I'll leave this open to consider for when performing a major version bump of this package.

**Comment by lukehoban** [comment] 2023-07-29 19:38
Closing out as by design for now.

**Closed by lukehoban** 2023-07-29 19:38 UTC
Labels: kind/enhancement, impact/usability, resolution/by-design
