### ISSUE TITLE
Golang concurrency errors with AWS ECR and Docker

### ISSUE THREAD

**Issue by JacksonKjar** [pulumi/pulumi-docker#300] opened 2021-07-21 00:20 UTC
I am trying to build a docker image and push it to an existing aws ecr repository using the golang sdk, but I am running into what appear to be concurrency errors when running `pulumi up`.
```
panic: sync: WaitGroup is reused before previous Wait has returned
    goroutine 1 [running]:
    sync.(*WaitGroup).Wait(0xc000373018)
        /usr/local/Cellar/go/1.16.3/libexec/src/sync/waitgroup.go:132 +0xae
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).wait(0xc000372f00, 0x0, 0x0)
        /Users/jacksonkjar/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.7.0/go/pulumi/context.go:156 +0x50
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunWithContext(0xc000372f00, 0x1a919c0, 0xc00003c06f, 0xb)
        /Users/jacksonkjar/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.7.0/go/pulumi/run.go:112 +0x2a6
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunErr(0x1a919c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/jacksonkjar/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.7.0/go/pulumi/run.go:84 +0x23f
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.Run(0x1a919c0, 0x0, 0x0, 0x0)
        /Users/jacksonkjar/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.7.0/go/pulumi/run.go:41 +0x59
    main.main()
        /Users/jacksonkjar/pulumi-test/main.go:11 +0x3e
    exit status 2

    error: an unhandled error occurred: program exited with non-zero exit code: 1
```
 I was following the documentation given at these links:
- https://www.pulumi.com/docs/reference/pkg/docker/image/
- https://www.pulumi.com/docs/reference/pkg/aws/ecr/getauthorizationtoken/

I am using pulumi v3.7.1 downloaded with homebrew on MacOs Catalina 10.15.7 and the official docker installation for MacOs (version 20.10.7)
## Steps to reproduce

```go
package main

import (
	"time"

	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/ecr"
	"github.com/pulumi/pulumi-docker/sdk/v3/go/docker"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		id := "******************"
		authRes, err := ecr.GetAuthorizationToken(ctx, &ecr.GetAuthorizationTokenArgs{
			RegistryId: &id,
		})
		if err != nil {
			return err
		}

		dockerImage, err := docker.NewImage(ctx, "example-app:test", &docker.ImageArgs{
			ImageName: pulumi.Sprintf("%s:%s", "****************.dkr.ecr.us-east-1.amazonaws.com/example",  "test"),
			Registry: docker.ImageRegistryArgs{
				Server:   pulumi.String(authRes.ProxyEndpoint),
				Username: pulumi.String(authRes.UserName),
				Password: pulumi.String(authRes.Password),
			},
		},
		)
		// uncomment to fix
		// time.Sleep(10 * time.Second)
		_ = dockerImage
		return err
	})
}

```

1. Create a golang pulumi project (defaults for everything)
2. Copy code into main.go
3. `$ pulumi up`
4. try a couple times and it should fail either in the preview or update phase (it has happened on both)

I found that if I insert a wait after calling docker.NewImage() it succeeds every time.
Is there perhaps something that I missed to establish a dependency?

Expected: 
successfully update stack without throwing errors

Actual: 
see above

**Comment by stack72** [comment] 2021-07-22 14:10
Hi @JacksonKjar 

Sorry you are hitting this issue - I believe this is related to https://github.com/pulumi/pulumi/issues/7275

I am going to close that out as this is a duplicate of that upstream issue which we will use as the central location for tracking this

Paul

**Closed by stack72** 2021-07-22 14:10 UTC
Labels: kind/bug, resolution/duplicate
