### ISSUE TITLE
`depends_on` in Python doesn't work as expected with `docker.Image`

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi-docker#336] opened 2022-02-19 01:03 UTC
Apologies if this is just something I'm doing wrong, but it looks like `depends_on` isn't causing `docker.Image` to wait before attempting to push to a remote repository. Here are two programs, one that works and one that doesn't:

This program works and uses an implicit dependency:
https://gist.github.com/cnunciato/28bd39767f02cb9c7f5809739aa03d90

This one does not and uses `depends_on`:
https://gist.github.com/cnunciato/215b59221021822e0d91cc9a9828464b

Interestingly, the same program works with `dependsOn` in TypeScript:
https://gist.github.com/cnunciato/32e9d52a5bd45e47dcdde71f6ac24c5f

So the problem appears to be specific to Python somehow.

**Comment by jkodroff** [comment] 2022-09-21 22:25
@cnunciato The problem is specific to Python because the current implementation of `docker.Image` is an overlay which has a separate implementation in each target language.

**Comment by uatach** [comment] 2022-12-15 01:04
Not sure if it's related but I'm trying to use the `docker.Image` into a `gcp.cloudrun.Service` but the resource for the service executes before the image is built and pushed, so the program fails with a 'image not found' error and using `depends_on` also does not seem to work as expected.

**Comment by jkodroff** [comment] 2023-01-04 19:24
@uatach That's precisely the issue I saw, and that's correct - `depends_on` does not work at all in the current Python implementation. @guineveresaenger is leading the active effort on a new implementation (version 4 of the provider) that will:

1. Behave the same in all languages
2. Obey the semantics of normal Pulumi resources (like `depends_on`).

**Comment by AaronFriel** [comment] 2023-03-09 02:01
This issue should be resolved with the new implementation of the [Docker Image resource in v4](https://github.com/pulumi/pulumi-docker/releases/tag/v4.0.0)! See our blog post for more info: https://www.pulumi.com/blog/build-images-50x-faster-docker-v4/

**Closed by AaronFriel** 2023-03-09 02:01 UTC
Labels: resolution/fixed, kind/bug
